baseURL = "https://www.raibaz.it"
languageCode = "it-it"
title = "Raibaz."
theme = "coder"
enableEmoji = true
googleAnalytics = "G-C88PX52YNP"

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']

[params]
  images = ["images/main-image.png"]

[markup.goldmark.renderer]
  unsafe = true
