[build]
  publish = "public"
  command = "hugo --minify -v --gc"

[context.production.environment]
  HUGO_VERSION = "0.142.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.142.0"

[[redirects]]
  from = "/rss"
  to = "/index.xml"
  status = 200

[[redirects]]
  from = "/feed"
  to = "/index.xml"
  status = 200
